### ISSUE TITLE
 SyntaxError: Unexpected token { (line:30)

### ISSUE THREAD

**Issue by claudiocastro** [DeanCording/node-red-contrib-google-action#10]
I had install this node using the "manage palette" option in node-red, but when i try to deploy the sample flow it show me the following message and stop all my flows till i remove the new nodes:

"Flows stopped due to missing node types.
google-action in
google-action response"

I took a look again at the palette and this message was under the node name "SyntaxError: Unexpected token { (line:30)"

I'm totally new with node and node-red so I dont really know where to look under the hood, I do know my way around the console so if there is any other info i can provide to ease up the diagnosis please let me know and i will provide it asap.

Regards,

**Comment by DeanCording** [comment]
I'm had a quick look but I can't see anything wrong with the code.  I'll look into it a bit deeper over the next day or so.

**Comment by claudiocastro** [comment]
Thanks for the quick response, i kept digging and after reinstall the module using npm directly i noticed an error, your node wants nodejs6 and raspbian only brings 4.something, so I'm upgrading nodejs/node-red right now and will try again.

Will let you know, thanks again!

**Comment by claudiocastro** [comment]
The issue was the nodejs version, This requires nodejs >= 6 and Raspian comes with 4.8.

The upgrade script available here: https://nodered.org/docs/hardware/raspberrypi worked like a charm, without losing any of my currently running flows.

Thanks!
