### ISSUE TITLE
start google play music

### ISSUE THREAD

**Issue by dkern** [DeanCording/node-red-contrib-google-action#15]
I know that google actions are capable to start music via stream on home devices. But I have no idea how to do this with this node. Is this even possible?

Thanks in advance.

**Comment by DeanCording** [comment]
You need to use Google Cast to start music streaming on home devices.  There are some Node libraries available but it is a difficult API to work with.

**Comment by dkern** [comment]
Well, yes. Cast API is for streaming media to the device. But that's not what i want. I want to tell the device what he has to do on it's own. Like when i say _hey google, play metallica_ (just for example), the device don't use the cast api, it just do it on its own. And I thought actions can execute these command on the device, or not?

I saw this example on the page here:
https://assistant.google.com/services/a/uid/000000d8bfc5c546?hl=en

There is just a button what sends the command to the device, just like a voice command. Not like with the cast api. Is this possible?

**Comment by JSzaszvari** [comment]
No, you need to use the APIs / Tools provided and can't go outside these.

That send to device on the page you linked is simply telling Google Play
music to start music using the cast API, it's not streaming directly

You can't 'execute commands' on the devices, only play in the sandbox
provided

**Comment by Paul-Reed** [comment]
Use Google Play music.
Just upload your music to Google's servers, and you can just say; "Hey Google, play my album Nothing but thieves"
No subscription needed.

**Comment by dkern** [comment]
Okay, i will go into the cast api again. I thought that is done by another way. I know that we're bound to the google-given things. ;)

And @Paul-Reed, that is an completely other thing. Do you even read what i wrote? If i would like to play my own music, thats really what the cast api is for. And i don't want to speak with my device in this example, as i wrote. But thank you anyway ...
