### ISSUE TITLE
SSL configuration

### ISSUE THREAD

**Issue by JBX028** [DeanCording/node-red-contrib-google-action#4]
Hi,
Can you briefly explain how I have to generate the ssl key and certificat? I already created such a files with openssl but I am not sure to understand from which location I have to run the command in regards of this plugin. Do I have to generate the file from the node module directory to make it available from the node-red console?

Thanks,
Regards,

**Comment by Paul-Reed** [comment]
I've put my SSL certificate & key files in `/home/pi/.node-red/ssl/`
And load them in the Action request node as `/home/pi/.node-red/ssl/ssl.key` & `/home/pi/.node-red/ssl/ssl.cert`

Paul

**Comment by JBX028** [comment]
Thanks!
