### ISSUE TITLE
Issue using on Raspberry Pi Node-Red

### ISSUE THREAD

**Issue by tanker11** [DeanCording/node-red-contrib-google-action#5]
Hello,

I have tried your node on my computer running on Windows and this is available in Node-Reds palette.
Doing the same thing on my Raspberry Pi, after the installation the node disappears from the palette.
When starting the node-red from the console I get the following message:
2 Feb 15:29:46 - [info] Node.js  version: v4.8.2
2 Feb 15:29:46 - [info] Linux 4.9.59-v7+ arm LE
2 Feb 15:29:47 - [info] Loading palette nodes
2 Feb 15:29:51 - [info] Dashboard version 2.7.0 started at /ui
2 Feb 15:29:53 - [warn] ------------------------------------------------------
2 Feb 15:29:53 - [warn] [google-action] SyntaxError: Unexpected token { (line:30)
2 Feb 15:29:53 - [warn] ------------------------------------------------------

I can't get over on this problem.
Do you have any idea what to check?

Thanks,

Robert

**Comment by DeanCording** [comment]
Can you do an `npm update` and check you have the latest version of actions-on-google.  It should be 1.6.1.  If you can check it on your Windows computer as well to see if there is any difference.

**Comment by tanker11** [comment]
Hello,
First of all, thanks very much for supporting.
I checked the versions: on both systems it is 1.1.0. And npm update did not
help.
But I checked npm and nodejs versions and they were old on my linux. So
updated and now it seems to start properly and keeps the node on palette.
Will further try later.
Now I need to find some more detailed descriptions how the app deployment
and connection mechanism works as I am not experienced with it and it did
not work for the first time...
Do you have a suggestuon besides google developer documents that are too
verbose and I cannot get the essence...

Regards,
Robert

2018. febr. 6. 9:44 ezt írta ("Dean Cording" <notifications@github.com>):

**Comment by DeanCording** [comment]
> Now I need to find some more detailed descriptions how the app deployment
and connection mechanism works as I am not experienced with it and it did
not work for the first time...

Do you mean the Google Action app? If so, there is very little to it.   Basically create a new project in the Google Actions console and note the project id.  Add the project id and your server address in the actions.json file, and then publish it using the gaction utility.  The details and links are in the [README.md](https://github.com/DeanCording/node-red-contrib-google-action/blob/master/README.md).

**Comment by tanker11** [comment]
Hello,

Indeed, based on your description I have already tried.
Requesting the following:
gactions test -preview_mins 9999999 -action_package action.json -project
MY_PROJECT_ID

In the action.json I entered my external IP with port 8081 (Is it right?)
and added a port forwarding rule to my internal IP.
Also entered the project ID to the first 'name' element (is it right? BTW
it is not in the description you linked...)
But I receive the following error:

ERROR: Failed to test the app for the Assistant
ERROR: The caller does not have permission
2018/02/06 18:11:04 Server did not return HTTP 200

Note, I also have self signed certificates for the server.

Thanks if you can "decode" the error message from google.

Robert

2018-02-06 16:12 GMT+01:00 Dean Cording <notifications@github.com>:

**Comment by tanker11** [comment]
Hello,

Sorry for bothering with the previous one.
I have been trying hard and find out some issues in my process (especially
a typo in my firewall rule).
All works now!

Thanks for the suport.

Robert

2018-02-06 16:12 GMT+01:00 Dean Cording <notifications@github.com>:
