### ISSUE TITLE
My test app isn't responding right now. Try again soon.

### ISSUE THREAD

**Issue by aleonnet** [DeanCording/node-red-contrib-google-action#6]
Hi @DeanCording 
Great job! I tried your node and it worked only once. The next day I keep receiving the following message from Assistant:
"My test app isn't responding right now. Try again soon."

What am I could possibly doing wrong?
Thanks for help.

**Comment by DeanCording** [comment]
That message means that Google can't connect to your Node Red server.  Do you still have the port open/forwarded on your  firewall?

**Comment by aleonnet** [comment]
Yes the port is open and port forward configured.

curl command results are below: 

curl -v https://abhome.homeip.net:8443/
* Hostname was NOT found in DNS cache
*   Trying 191.163.159.73...
* Connected to abhome.homeip.net (191.163.159.73) port 8443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: self signed certificate
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):
curl: (60) SSL certificate problem: self signed certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by DeanCording** [comment]
Yep, I can reach it from here as well.

You may need to reinstall your app on Google using the gactions command.  I noticed mine had stopped working and Google has updated gactions, so they may have stopped all test apps.

**Comment by aleonnet** [comment]
./gactions test -preview_mins 9999999 -action_package action.json -project nodered-cb878
I tried but got same result :( unfortunately.

**Comment by DeanCording** [comment]
You can also get that error if your flow doesn't respond.  Do you see any messages in Node Red coming in from google-action? Any errors happening?  Is the flow connected to the google-action out node?

**Comment by aleonnet** [comment]
No message in Node Red (I'm using you example flow).
I've even reinstalled the node (npm i node-red-contrib-google-action) and nothing changed.

**Comment by aleonnet** [comment]
I changed the action resquest URL from abhome.homeip.net to / and it worked!

**Comment by Paul-Reed** [comment]
Strange. I've just tried my test app and it's stopped working too.
It has previously worked fine, and I haven't changed anything..

**Comment by aleonnet** [comment]
I remember it worked before with my own URL... I had to change the URL to '/' in the node in order to make it work... but I did a lot of things until reach this point...

**Comment by Paul-Reed** [comment]
Well I got mine back working by reloading the app in https://console.actions.google.com/ again.
All good now!
