### ISSUE TITLE
App returned an HTTP error. State: URL_TIMEOUT

### ISSUE THREAD

**Issue by GAZ082** [DeanCording/node-red-contrib-google-action#8]
Hi Dean. I tried to follow the example you made:

```
{
  "actions": [
    {
      "description": "Default Welcome Intent",
      "name": "MAIN",
      "fulfillment": {
        "conversationName": "nodeRedApp"
      },
      "intent": {
        "name": "actions.intent.MAIN",
        "trigger": {
          "queryPatterns": ["talk to Node Red"]
        }
      }
    }
  ],
  "conversations": {
    "nodeRedApp": {
      "name": "nodeRedApp",
      "url": "https://mysite.me:8081/", <<<<<<< my setting
      "fulfillmentApiVersion": 2,
      "in_dialog_intents": [
        {
          "name": "actions.intent.CANCEL"
        }
      ]
    }
  }
}

```

Used your example flow and just modified like this:
![image](https://user-images.githubusercontent.com/100194/42406578-d00a811c-8180-11e8-977d-3164fc33e330.png)

And yet when i try it out, i get the error in the subject. Any tips? Thanks a lot!

**Comment by DeanCording** [comment]
Where does the error show - Node red or Google Action Console?

**Comment by GAZ082** [comment]
In the ga console emulator. Node red log shows nothing.

**Comment by DeanCording** [comment]
If you don't get anything in the Node Red log then it is likely a connection problem with Google Action.
Do you have a firewall?  Is it set to forward the 8081 port to your Node Red server?  Are there any outgoing filters that may block a response?
You can try to connect to your Node Red server using a browser on an external network to check that you can connect.

**Comment by GAZ082** [comment]
The port needed is the one of ND right? Not the broker. If so, i do can access ND with 1880 from outside the network, i edit nodes from work and also use the dashboard.

This is what i'm getting:

![image](https://user-images.githubusercontent.com/100194/42512540-428ec91c-842b-11e8-81bb-802d9ff27761.png)

The log outputs anything related to Actions? Even if everything is ok?

**Comment by DeanCording** [comment]
No, the Google Action node runs of a different port (defaults to 8081) so that you don't need to expose your Node Red server to on the Internet.

Test that you can connect to the 8081 port from an external network.

**Comment by GAZ082** [comment]
Looks like the port is blocked. Thanks! I'll have some fun tonight and if works i'll close this up!

**Comment by GAZ082** [comment]
The port is now open and is just the same. This is the error im getting from GA debug console:

```
{
 insertId:  "ziqzs5g38x4a2z"  
 labels: {
  channel:  "preview"   
  querystream:  "GOOGLE_USER"   
  source:  "AOG_REQUEST_RESPONSE"   
 }
 logName:  "projects/yadayada/logs/actions.googleapis.com%2Factions"  
 receiveTimestamp:  "2018-07-11T23:12:14.161638607Z"  
 resource: {
  labels: {
   action_id:  "actions.intent.MAIN"    
   project_id:  "yadayada"    
   version_id:  ""    
  }
  type:  "assistant_action"   
 }
 severity:  "ERROR"  
 textPayload:  "App returned an HTTP error. State: URL_TIMEOUT"  
 timestamp:  "2018-07-11T23:12:14.146621250Z"  
 trace:  "projects/yadayada/traces/1531350716117"  
}

```
It does not give me useful information.

I tried several options for the URL in the action file i have to upload, with trailing slash, without, with www, without, nothing.

Is there a way to get a more verbose output?

**Comment by DeanCording** [comment]
It sounds like it is connecting but not getting a response.

Have you connected the Google Action In node to the Google Action Response node in Node Red?

**Comment by GAZ082** [comment]
Yeah, I used the example you posted and configured the action request as in the picture.

The odd thing is the Action In does not output anything to the debugger node. Should it?

**Comment by GAZ082** [comment]
Could you confirm how you configured the URL part in the action.json and in the node?

**Comment by DeanCording** [comment]
The configuration I use is exactly the same as you have shown in the first comment.  The Action In should output a msg when it receives a connection/request, even just from a browser.

The following msg is output when I connect to my Node Red Google Action server from a browser:

`{"conversationId":null,"intent":null,"dialogState":  {},"closeConversation":true,"userId":0,"locale":"","payload":null,"_msgid":"801af899.96e9d8"}`

**Comment by GAZ082** [comment]
Silly me! I was redirecting to a wrong server from the router! It's communicating! Haha! Thanks for the patience!
